#!/bin/bash

set -e

unswap_single() {
	swapoff -v "$1" && swapon -v "$1"
}

if [ "$#" -gt 0 ]; then
	for swapdev in "$@"; do
		unswap_single "$swapdev"
	done
else
	(read ; while read swapdev type size used prio; do
		if [ "$used" -gt 0 ]; then
			unswap_single "$swapdev"
		fi
	done) < /proc/swaps
fi
